version: '3.1'

services:
  postgres:
    image: postgres:16
    container_name: postgres-store
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: medusa
    volumes:
      - pgdata:/var/lib/postgresql/data
    hostname: localhost
    ports:
      - 5432:5432

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@mail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - 9090:80

volumes:
  pgdata:
